services:
  - type: web
    name: fastapi-transcriber-backend
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend:app --host 0.0.0.0 --port $PORT"

  - type: web
    name: flask-transcriber-ui
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn frontend:app --bind 0.0.0.0:$PORT"
