services:
  - type: web
    name: flask-transcriber-ui
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn frontend:app"
    plan: free

